# JuliaFormatter configuration
# 不要把参数和返回值分行排版

margin = 120                   # 行宽大一些，避免过早换行
always_for_in = true           # 与函数无关，但常用
whitespace_typedefs = true
remove_extra_newlines = true

# 最关键的两个 ↓↓↓
format_docstrings = false
short_to_long_function_def = false     # 超过 margin 才展开成多行