[boundary]
PRINT_BOUNDARY_CONDITION = true
BOUNDARY_SHOW_PLOTS = false

[model]
MODEL_CONSIDER_BESS = 0
MODEL_CONSIDER_DATA_CENTER = 0
MODEL_CONSIDER_FREQUENCY_CONTROL = 0
MODEL_CONSIDER_MULTI_CUTS = 1

[ccg]
CCG_SCENARIO_LIMIT = 6
CCG_INITIAL_SCENARIOS = 2
CCG_SCENARIOS_PER_ITERATION = 1
CCG_MAX_ITERATIONS = 3
CCG_PARALLEL_RECOURSE = false

[dro]
CCG_DRO_ENABLED = true
CCG_DRO_RADIUS = 0.05
CCG_WASSERSTEIN_POWER = 1.0
