[boundary]
PRINT_BOUNDARY_CONDITION = true
BOUNDARY_SHOW_PLOTS = false

[model]
MODEL_CONSIDER_BESS = 0
MODEL_CONSIDER_DATA_CENTER = 0
MODEL_CONSIDER_FREQUENCY_CONTROL = 0
MODEL_CONSIDER_MULTI_CUTS = 1

[benders]
BENDERS_SCENARIO_LIMIT = 2
BENDERS_MAX_ITERATIONS = 1
BENDERS_VERBOSE_CUTS = false
BENDERS_ENABLE_JENSEN_CUT = false
BENDERS_FAST_DIRECT_SOLVE = false

[benders.subproblems]
BENDERS_PARALLEL_SUBPROBLEMS = false
