# ======================================================================
# PowerSystems.jl native integration & solving demo for Revised Branch
# ======================================================================
# This script demonstrates:
#   1. Loading a native PowerSystems.System case via PowerSystemCaseBuilder;
#   2. Adding custom thermal generator frequency regulation parameters;
#   3. Mounting data centers on specified network buses;
#   4. Running three different solving algorithms:
#      - Method A: Extensive-Form SCUC (Benchmark UC)
#      - Method B: Benders Decomposition
#      - Method C: Column-and-Constraint Generation (CCG)
#
# Run this script from the repository root:
#   julia --project=. examples/powersystems_algorithms_demo.jl
# ======================================================================

using Pkg
const PROJECT_ROOT = normpath(joinpath(@__DIR__, ".."))
cd(PROJECT_ROOT)
Pkg.activate(PROJECT_ROOT)

using PowerSystems
using PowerSystemCaseBuilder
using JuMP
using Gurobi

# Include toolkit configurations and algorithms
include("../src/environment_config.jl")
include("../src/renewables/stochastic_simulation.jl")
include("../src/input_data/readers.jl")
include("../src/unit_commitment/unit_commitment_model.jl")
include("../tools/benders/setup.jl")
include("../tools/ccg/ccg_solver.jl")
include("../tools/benchmark/benchmark_uc.jl")

println("======================================================================")
println("Running PowerSystems native case & solving pipeline demo...")
println("======================================================================")

# ----------------------------------------------------------------------
# Step 1: Build the native PowerSystems case
# ----------------------------------------------------------------------
# We use the built-in 5-bus system "c_sys5_all_components" under PSITestSystems.
case_name = "c_sys5_all_components"
println("Building native PowerSystems System: $case_name...")
sys = build_system_from_powersystems(case_name; case_category = PSITestSystems)

# ----------------------------------------------------------------------
# Step 2: Configure custom frequency parameters for conventional units
# ----------------------------------------------------------------------
# Map conventional generator names to their frequency parameters:
#   - H: Inertia constant (s)
#   - D: Damping coefficient (p.u.)
#   - K: Governor gain
#   - F: Fraction of total power generated by the turbine
#   - T: Governor time constant (s)
#   - R: Governor speed regulation (droop) (p.u.)
frequency_params = Dict(
    "Solitude" => (H = 7.0, D = 0.061, K = 0.9, F = 0.15, T = 8.0, R = 0.06),
    "Park City" => (H = 5.5, D = 0.121, K = 0.95, F = 0.35, T = 7.0, R = 0.06),
    "Alta" => (H = 3.5, D = 0.181, K = 0.98, F = 0.25, T = 9.0, R = 0.06),
    "Brighton" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
    "Sundance" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
)

# ----------------------------------------------------------------------
# Step 3: Configure custom data centers to mount
# ----------------------------------------------------------------------
# Mount data centers on specific network buses with tasks/workloads and capacities:
#   - bus: Bus number where the data center is located
#   - p_max: Maximum active power demand (MW)
#   - p_min: Minimum active power demand (MW)
#   - idle_power: Idle server power consumption (MW)
#   - server_energy: Energy conversion multiplier
#   - lambda: Task arrival rate
#   - mu: Server processing/service rate
#   - workload: Time-series computational task curve
data_centers = [
    (bus = 3, p_max = 0.5, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
    (bus = 4, p_max = 0.3, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
]

# Set environment controls for model options.
# Note: MODEL_CONSIDER_FREQUENCY_CONTROL is set to 0 here so that all three methods 
# solve the identical formulation and their objectives match (since the Benders 
# subproblem ignores frequency constraints by design).
withenv(
    "MODEL_CONSIDER_BESS" => "0", # Disable BESS since c_sys5 doesn't contain battery storage components by default
    "MODEL_CONSIDER_FREQUENCY_CONTROL" => "0",
    "MODEL_CONSIDER_DATA_CENTER" => "1",
) do
    # ----------------------------------------------------------------------
    # Method A: Solve via Extensive-Form SCUC (Benchmark)
    # ----------------------------------------------------------------------
    println("\n[Method A] Solving Extensive-Form SCUC (Benchmark)...")
    res_extensive = solve_benchmark_uc_powersystems(
        sys,
        ""; # Empty case_dir since loading directly from System
        scenario_limit = 3,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    println("→ Extensive-Form Solving Complete. Status: ", res_extensive.status)
    println("→ Objective Value: ", res_extensive.upper_bound)

    # ----------------------------------------------------------------------
    # Method B: Solve via Benders Decomposition
    # ----------------------------------------------------------------------
    println("\n[Method B] Solving via Benders Decomposition...")
    # 1. Initialize Benders Master and Subproblem models
    setup = main(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    scuc_masterproblem, scuc_subproblem = setup.master_model, setup.sub_model
    master_model_struct = setup.master_struct
    batch_sub_model_struct_dic = setup.batch_subproblems
    config_param, units, loads, winds = setup.config_param, setup.units, setup.loads, setup.winds
    NB, NG, NL, ND, NS, NT, NC, ND2, DataCentras = setup.NB, setup.NG, setup.NL, setup.ND, setup.NS, setup.NT, setup.NC, setup.ND2, setup.DataCentras
    psses = setup.psses

    # 2. Build auxiliary Jensen cuts structure if multi-cut mode is active
    NW = Int64(length(winds.index))
    jensen_subproblem_struct = if get(ENV, "BENDERS_ENABLE_JENSEN_CUT", "0") == "1" && config_param.is_ConsiderMultiCUTs == 1
        build_jensen_subproblem_for_mean_scenario(NT, NB, NL, NG, ND, NC, ND2, NW, units, winds, loads, lines, DataCentras, psses, config_param)
    else
        nothing
    end

    # 3. Solve using Benders decomposition loop
    res_benders = multiple_bender_decomposition_scuc(
        scuc_masterproblem,
        scuc_subproblem,
        master_model_struct,
        batch_sub_model_struct_dic,
        winds,
        config_param,
        NG,
        NT,
        NW,
        ND,
        NL;
        jensen_subproblem_struct = jensen_subproblem_struct,
    )
    println("→ Benders Solving Complete. Status: ", res_benders.status)
    println("→ Benders Upper Bound: ", res_benders.upper_bound)
    println("→ Benders Lower Bound: ", res_benders.lower_bound)

    # ----------------------------------------------------------------------
    # Method C: Solve via Column-and-Constraint Generation (CCG)
    # ----------------------------------------------------------------------
    println("\n[Method C] Solving via Column-and-Constraint Generation (CCG)...")
    res_ccg = solve_ccg_unit_commitment(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    println("→ CCG Solving Complete. Status: ", res_ccg.status)
    println("→ CCG Upper Bound: ", res_ccg.upper_bound)
    println("→ CCG Lower Bound: ", res_ccg.lower_bound)

    # ----------------------------------------------------------------------
    # Print Comparison Report
    # ----------------------------------------------------------------------
    println("\n=======================================================")
    println("DEMO RESULTS COMPARISON:")
    println("=======================================================")
    println("Extensive Form Objective: ", res_extensive.upper_bound)
    println("Benders Upper Bound:      ", res_benders.upper_bound)
    println("CCG Upper Bound:          ", res_ccg.upper_bound)
    println("=======================================================")

    if abs(res_extensive.upper_bound - res_benders.upper_bound) < 1e-2 && abs(res_extensive.upper_bound - res_ccg.upper_bound) < 1e-2
        println("SUCCESS: All three solving methods converge to the identical optimal objective!")
    else
        println("WARNING: Objective variance detected between methods.")
    end
end
