# ==============================================================================
# PowerSystems.jl Integration & Algorithms Comparative Solve Example
# ==============================================================================
#
# This script demonstrates how to:
# 1. Load a native PowerSystems case (c_sys5_all_components).
# 2. Configure conventional unit frequency regulation parameters.
# 3. Mount data center computational loads onto specific network buses.
# 4. Resolve the unit commitment problem using three algorithms:
#    - Extensive-Form (Direct Solve)
#    - Benders Decomposition
#    - Column-and-Constraint Generation (CCG)
#
# This script demonstrates how to:
# 1. Load a native PowerSystems case (c_sys5_all_components).
# 2. Configure conventional unit frequency regulation parameters.
# 3. Mount data center computational loads onto specific network buses.
# 4. Solve the unit commitment problem with three algorithms:
#    - Extensive form (direct solve)
#    - Benders decomposition
#    - Column-and-Constraint Generation (CCG)
#
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Environment & Path Setup
# ------------------------------------------------------------------------------
# We locate the project root relative to the directory of this file.
# Locate the project root relative to this file.
const DOCS_DIR = @__DIR__
const PROJECT_ROOT = dirname(DOCS_DIR)

# Include the core codebase components.
# Include the core codebase components.
include(joinpath(PROJECT_ROOT, "src", "environment_config.jl"))
include(joinpath(PROJECT_ROOT, "src", "renewables", "stochastic_simulation.jl"))
include(joinpath(PROJECT_ROOT, "src", "input_data", "readers.jl"))
include(joinpath(PROJECT_ROOT, "src", "unit_commitment", "unit_commitment_model.jl"))

# Include the Benders decomposition solver files.
# Include the Benders decomposition solver files.
include(joinpath(PROJECT_ROOT, "tools", "benders", "setup.jl"))
include(joinpath(PROJECT_ROOT, "tools", "benders", "decomposition.jl"))

# Include the Column-and-Constraint Generation (CCG) solver files.
# Include the Column-and-Constraint Generation solver files.
include(joinpath(PROJECT_ROOT, "tools", "ccg", "ccg_solver.jl"))

# Include the Extensive-Form benchmark solver files.
# Include the extensive-form benchmark solver files.
include(joinpath(PROJECT_ROOT, "tools", "benchmark", "benchmark_uc.jl"))

using PowerSystems
using PowerSystemCaseBuilder
using JuMP
using Gurobi

# ------------------------------------------------------------------------------
# 2. Build PowerSystems Case
# ------------------------------------------------------------------------------
# We build a built-in 5-bus system containing thermal generators, lines, and loads.
# Build a native five-bus system containing thermal generators, lines, and loads.
case_name = "c_sys5_all_components"
println("Building native PowerSystems System: $case_name...")
sys = build_system_from_powersystems(case_name; case_category = PSITestSystems)

# ------------------------------------------------------------------------------
# 3. Configure Frequency Regulation Parameters
# ------------------------------------------------------------------------------
# Define custom frequency parameters for conventional units:
#   - H: Inertia constant (s)
#   - D: Damping coefficient (p.u.)
#   - K: Governor gain
#   - F: Fraction of turbine power generated by the reheat section
#   - T: Governor time constant (s)
#   - R: Governor speed regulation (droop) (p.u.)
#
# Note: For units Brighton & Sundance, they do not participate in frequency control.
# To prevent division-by-zero errors in nadir fitting, we set their droop R to 1.0.
# Note: Brighton and Sundance do not participate in frequency control. Their droop R is set
# to 1.0 to prevent division-by-zero errors during nadir fitting.
frequency_params = Dict(
    "Solitude" => (H = 7.0, D = 0.061, K = 0.9, F = 0.15, T = 8.0, R = 0.06),
    "Park City" => (H = 5.5, D = 0.121, K = 0.95, F = 0.35, T = 7.0, R = 0.06),
    "Alta" => (H = 3.5, D = 0.181, K = 0.98, F = 0.25, T = 9.0, R = 0.06),
    "Brighton" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
    "Sundance" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
)

# ------------------------------------------------------------------------------
# 4. Configure Data Centers to Mount
# ------------------------------------------------------------------------------
# We configure data center workloads and capacities on network buses:
#   - bus: Bus number where the data center is located
#   - p_max / p_min: Active power limits (MW)
#   - idle_power: Idle server power consumption (MW)
#   - server_energy: Energy conversion multiplier
#   - lambda / mu: Queuing service arrival and process rate
#   - workload: Queue workload across time steps
#
# We mount data centers on Bus 3 (0.5 MW max) and Bus 4 (0.3 MW max).
# Mount data centers on Bus 3 (0.5 MW maximum) and Bus 4 (0.3 MW maximum).
data_centers = [
    (bus = 3, p_max = 0.5, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
    (bus = 4, p_max = 0.3, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
]

# ------------------------------------------------------------------------------
# 5. Comparative Execution of Algorithms
# ------------------------------------------------------------------------------
# We wrap the solves in a `withenv` block to control model option flags:
#   - MODEL_CONSIDER_BESS=0: Disable BESS since the case has no storage components.
#   - MODEL_CONSIDER_FREQUENCY_CONTROL=0: Set to 0 to align Benders & CCG formulations 
#     (as the Benders subproblems ignore frequency constraints by design).
#   - MODEL_CONSIDER_DATA_CENTER=1: Enable data center scheduling constraints.
#
# Run the solves inside a `withenv` block to control model option flags:
#   - MODEL_CONSIDER_BESS=0: Disable BESS because the case has no storage components.
#   - MODEL_CONSIDER_FREQUENCY_CONTROL=0: Align Benders and CCG formulations because
#     Benders subproblems intentionally ignore frequency constraints.
#   - MODEL_CONSIDER_DATA_CENTER=1: Enable data center scheduling constraints.
withenv("MODEL_CONSIDER_BESS" => "0", "MODEL_CONSIDER_FREQUENCY_CONTROL" => "0", "MODEL_CONSIDER_DATA_CENTER" => "1") do

    # --------------------------------------------------------------------------
    # Method A: Extensive-Form (Direct Solve)
    # Method A: Extensive Form (Direct Solve)
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method A] Solving via Extensive-Form (Direct Solve)...")
    println("=======================================================")
    res_extensive = solve_benchmark_uc_powersystems(
        sys,
        ""; # Empty case_dir because the System object is loaded directly.
        scenario_limit = 3,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    val_extensive = res_extensive.upper_bound
    println("-> Extensive Form Objective: $val_extensive")

    # --------------------------------------------------------------------------
    # Method B: Benders Decomposition
    # Method B: Benders Decomposition
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method B] Solving via Benders Decomposition...")
    println("=======================================================")
    # 1. Initialize Benders Master and Subproblems algebraically.
    # 1. Initialize the Benders master and subproblems algebraically.
    setup = main(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    scuc_masterproblem, scuc_subproblem = setup.master_model, setup.sub_model
    master_model_struct = setup.master_struct
    batch_sub_model_struct_dic = setup.batch_subproblems
    config_param, units, loads, winds = setup.config_param, setup.units, setup.loads, setup.winds
    NG, NT, ND, NL = setup.NG, setup.NT, setup.ND, setup.NL

    # 2. Execute Benders iterative decomposition.
    # 2. Execute the iterative Benders decomposition.
    res_benders = multiple_bender_decomposition_scuc(
        scuc_masterproblem, scuc_subproblem, master_model_struct, batch_sub_model_struct_dic,
        winds, config_param, NG, NT, length(winds.index), ND, NL,
    )
    val_benders = res_benders.upper_bound
    println("-> Benders Upper Bound: $val_benders")

    # --------------------------------------------------------------------------
    # Method C: Column-and-Constraint Generation (C&CG)
    # Method C: Column-and-Constraint Generation (CCG)
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method C] Solving via CCG Solver...")
    println("=======================================================")
    # Execute Column-and-Constraint Generation (CCG) solver directly using keyword arguments.
    # Execute the CCG solver directly with keyword arguments.
    res_ccg = solve_ccg_unit_commitment(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    val_ccg = res_ccg.upper_bound
    println("-> CCG Upper Bound: $val_ccg")

    # --------------------------------------------------------------------------
    # Comparison Summary
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("DEMO COMPARISON RESULTS:")
    println("=======================================================")
    println("Extensive Form Objective: ", val_extensive)
    println("Benders Upper Bound:      ", val_benders)
    println("CCG Upper Bound:          ", val_ccg)
    println("=======================================================")

    # Check if the objectives match up to a small numerical tolerance.
    # Check whether the objective values match within numerical tolerance.
    if abs(val_extensive - val_benders) < 1e-2 && abs(val_extensive - val_ccg) < 1e-2
        println("SUCCESS: All three solving methods converge to the identical optimal objective!")
        println("SUCCESS: all three solving methods converged to the same optimal objective.")
    else
        println("WARNING: Objective variance detected between methods.")
        println("WARNING: objective differences were detected between methods.")
    end
    return println("=======================================================")
end