# ==============================================================================
# PowerSystems.jl Integration & Algorithms Comparative Solve Example
# PowerSystems.jl 整合与多种算法求解对比示例
# ==============================================================================
#
# This script demonstrates how to:
# 1. Load a native PowerSystems case (c_sys5_all_components).
# 2. Configure conventional unit frequency regulation parameters.
# 3. Mount data center computational loads onto specific network buses.
# 4. Resolve the unit commitment problem using three algorithms:
#    - Extensive-Form (Direct Solve)
#    - Benders Decomposition
#    - Column-and-Constraint Generation (CCG)
#
# 本脚本演示了如何：
# 1. 加载原生 PowerSystems 算例 (c_sys5_all_components)；
# 2. 配置常规发电机组的调频参数；
# 3. 将数据中心计算负荷挂载到特定网络总线（Bus）上；
# 4. 调用以下三种算法求解单位组合问题：
#    - 扩展形式 (直接求解)
#    - Benders 分解法
#    - 栏与约束生成算法 (CCG)
#
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Environment & Path Setup | 环境与路径设置
# ------------------------------------------------------------------------------
# We locate the project root relative to the directory of this file.
# 我们根据此文件所在目录定位项目根目录。
const DOCS_DIR = @__DIR__
const PROJECT_ROOT = dirname(DOCS_DIR)

# Include the core codebase components.
# 引入核心代码库组件。
include(joinpath(PROJECT_ROOT, "src", "environment_config.jl"))
include(joinpath(PROJECT_ROOT, "src", "renewables", "stochastic_simulation.jl"))
include(joinpath(PROJECT_ROOT, "src", "input_data", "readers.jl"))
include(joinpath(PROJECT_ROOT, "src", "unit_commitment", "unit_commitment_model.jl"))

# Include the Benders decomposition solver files.
# 引入 Benders 分解求解器文件。
include(joinpath(PROJECT_ROOT, "tools", "benders", "setup.jl"))
include(joinpath(PROJECT_ROOT, "tools", "benders", "decomposition.jl"))

# Include the Column-and-Constraint Generation (CCG) solver files.
# 引入 CCG 求解器文件。
include(joinpath(PROJECT_ROOT, "tools", "ccg", "ccg_solver.jl"))

# Include the Extensive-Form benchmark solver files.
# 引入扩展形式基准求解器文件。
include(joinpath(PROJECT_ROOT, "tools", "benchmark", "benchmark_uc.jl"))

using PowerSystems
using PowerSystemCaseBuilder
using JuMP
using Gurobi

# ------------------------------------------------------------------------------
# 2. Build PowerSystems Case | 构建 PowerSystems 算例
# ------------------------------------------------------------------------------
# We build a built-in 5-bus system containing thermal generators, lines, and loads.
# 我们构建一个包含火电机组、线路和负荷的原生五节点系统。
case_name = "c_sys5_all_components"
println("Building native PowerSystems System: $case_name...")
sys = build_system_from_powersystems(case_name; case_category = PSITestSystems)

# ------------------------------------------------------------------------------
# 3. Configure Frequency Regulation Parameters | 配置调频参数
# ------------------------------------------------------------------------------
# Define custom frequency parameters for conventional units:
#   - H: Inertia constant (s) | 惯性常数 (秒)
#   - D: Damping coefficient (p.u.) | 阻尼系数 (标幺值)
#   - K: Governor gain | 调速器增益
#   - F: Fraction of turbine power generated by the reheat section | 汽轮机再热器出力比例
#   - T: Governor time constant (s) | 调速器时间常数 (秒)
#   - R: Governor speed regulation (droop) (p.u.) | 调速器调差率/静差率 (标幺值)
#
# Note: For units Brighton & Sundance, they do not participate in frequency control.
# To prevent division-by-zero errors in nadir fitting, we set their droop R to 1.0.
# 注意：Brighton 和 Sundance 机组不参与调频。为防止频率最低点拟合时发生除以零的错误，
# 我们将它们的调差率 R 设为 1.0。
frequency_params = Dict(
    "Solitude" => (H = 7.0, D = 0.061, K = 0.9, F = 0.15, T = 8.0, R = 0.06),
    "Park City" => (H = 5.5, D = 0.121, K = 0.95, F = 0.35, T = 7.0, R = 0.06),
    "Alta" => (H = 3.5, D = 0.181, K = 0.98, F = 0.25, T = 9.0, R = 0.06),
    "Brighton" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
    "Sundance" => (H = 5.0, D = 0.0, K = 0.0, F = 0.0, T = 0.0, R = 1.0),
)

# ------------------------------------------------------------------------------
# 4. Configure Data Centers to Mount | 配置要挂载的数据中心
# ------------------------------------------------------------------------------
# We configure data center workloads and capacities on network buses:
#   - bus: Bus number where the data center is located | 数据中心挂载的节点编号
#   - p_max / p_min: Active power limits (MW) | 有功功率上限/下限 (兆瓦)
#   - idle_power: Idle server power consumption (MW) | 静态/空闲服务器功耗 (兆瓦)
#   - server_energy: Energy conversion multiplier | 服务器能效换算乘数
#   - lambda / mu: Queuing service arrival and process rate | 排队服务到达率与处理率
#   - workload: Queue workload across time steps | 各时间步的计算负载队列
#
# We mount data centers on Bus 3 (0.5 MW max) and Bus 4 (0.3 MW max).
# 我们在 3 号节点 (最大 0.5 MW) 和 4 号节点 (最大 0.3 MW) 挂载数据中心。
data_centers = [
    (bus = 3, p_max = 0.5, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
    (bus = 4, p_max = 0.3, p_min = 0.0, idle_power = 0.0, server_energy = 0.0, lambda = 0.0, mu = 1.0, workload = fill(0.0, 24)),
]

# ------------------------------------------------------------------------------
# 5. Comparative Execution of Algorithms | 各算法对比执行
# ------------------------------------------------------------------------------
# We wrap the solves in a `withenv` block to control model option flags:
#   - MODEL_CONSIDER_BESS=0: Disable BESS since the case has no storage components.
#   - MODEL_CONSIDER_FREQUENCY_CONTROL=0: Set to 0 to align Benders & CCG formulations 
#     (as the Benders subproblems ignore frequency constraints by design).
#   - MODEL_CONSIDER_DATA_CENTER=1: Enable data center scheduling constraints.
#
# 我们在 `withenv` 块内执行求解，以控制模型选项标志：
#   - MODEL_CONSIDER_BESS=0: 禁用电池储能（因为此算例默认不含储能组件）；
#   - MODEL_CONSIDER_FREQUENCY_CONTROL=0: 设为 0 以对齐 Benders 与 CCG 的模型形式
#     （因为 Benders 子问题在设计上忽略了频率约束）；
#   - MODEL_CONSIDER_DATA_CENTER=1: 启用数据中心调度约束。
withenv("MODEL_CONSIDER_BESS" => "0", "MODEL_CONSIDER_FREQUENCY_CONTROL" => "0", "MODEL_CONSIDER_DATA_CENTER" => "1") do

    # --------------------------------------------------------------------------
    # Method A: Extensive-Form (Direct Solve)
    # 方法 A：扩展形式（直接求解）
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method A] Solving via Extensive-Form (Direct Solve)...")
    println("=======================================================")
    res_extensive = solve_benchmark_uc_powersystems(
        sys,
        ""; # Empty case_dir since loading directly from System object | 直接从系统对象加载，case_dir 留空
        scenario_limit = 3,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    val_extensive = res_extensive.upper_bound
    println("→ Extensive Form Objective: $val_extensive")

    # --------------------------------------------------------------------------
    # Method B: Benders Decomposition
    # 方法 B：Benders 分解法
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method B] Solving via Benders Decomposition...")
    println("=======================================================")
    # 1. Initialize Benders Master and Subproblems algebraically.
    # 1. 代数化初始化 Benders 主问题与子问题。
    setup = main(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    scuc_masterproblem, scuc_subproblem = setup.master_model, setup.sub_model
    master_model_struct = setup.master_struct
    batch_sub_model_struct_dic = setup.batch_subproblems
    config_param, units, loads, winds = setup.config_param, setup.units, setup.loads, setup.winds
    NG, NT, ND, NL = setup.NG, setup.NT, setup.ND, setup.NL

    # 2. Execute Benders iterative decomposition.
    # 2. 执行 Benders 迭代分解求解。
    res_benders = multiple_bender_decomposition_scuc(
        scuc_masterproblem, scuc_subproblem, master_model_struct, batch_sub_model_struct_dic,
        winds, config_param, NG, NT, length(winds.index), ND, NL,
    )
    val_benders = res_benders.upper_bound
    println("→ Benders Upper Bound: $val_benders")

    # --------------------------------------------------------------------------
    # Method C: Column-and-Constraint Generation (C&CG)
    # 方法 C：栏与约束生成算法 (CCG)
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("[Method C] Solving via CCG Solver...")
    println("=======================================================")
    # Execute Column-and-Constraint Generation (CCG) solver directly using keyword arguments.
    # 直接使用关键字参数执行栏与约束生成算法（CCG）求解。
    res_ccg = solve_ccg_unit_commitment(;
        scenario_limit = 3,
        use_powersystems = true,
        sys = sys,
        frequency_parameters = frequency_params,
        data_centers = data_centers,
        horizon = 24,
    )
    val_ccg = res_ccg.upper_bound
    println("→ CCG Upper Bound: $val_ccg")

    # --------------------------------------------------------------------------
    # Comparison Summary | 对比总结报告
    # --------------------------------------------------------------------------
    println("\n=======================================================")
    println("DEMO COMPARISON RESULTS:")
    println("=======================================================")
    println("Extensive Form Objective: ", val_extensive)
    println("Benders Upper Bound:      ", val_benders)
    println("CCG Upper Bound:          ", val_ccg)
    println("=======================================================")

    # Check if the objectives match up to a small numerical tolerance.
    # 检查各方法的目标函数值是否在数值误差范围内一致。
    if abs(val_extensive - val_benders) < 1e-2 && abs(val_extensive - val_ccg) < 1e-2
        println("SUCCESS: All three solving methods converge to the identical optimal objective!")
        println("成功：三种求解方法均收敛于完全相同的最优目标函数值！")
    else
        println("WARNING: Objective variance detected between methods.")
        println("警告：检测到不同求解方法之间存在目标函数值偏差。")
    end
    return println("=======================================================")
end
